name: Azure CI/CD for React App with B2C Auth

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_ENV_NAME: a-riff-in-react
  AZURE_LOCATION: eastus

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build React app
        run: npm run build
        env:
          # These placeholder values are needed for build but will be replaced by actual values in Azure
          VITE_B2C_CLIENT_ID: "placeholder-for-build"
          VITE_B2C_TENANT_NAME: "placeholder-for-build"
          VITE_B2C_SIGNIN_POLICY: "placeholder-for-build"
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Azure Infrastructure with B2C Configuration
        id: deploy-bicep
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./infra/main.bicep
          parameters: >
            environmentName=${{ env.AZURE_ENV_NAME }}
            location=${{ env.AZURE_LOCATION }}
            b2cTenantName=${{ secrets.B2C_TENANT_NAME }}
            b2cClientId=${{ secrets.B2C_CLIENT_ID }}
            b2cSigninPolicy=${{ secrets.B2C_SIGNIN_POLICY }}
            sqlAdminPassword=${{ secrets.SQL_ADMIN_PASSWORD }}
          deploymentName: a-riff-in-react-${{ github.run_number }}
          failOnStdErr: false
      
      - name: Deploy React app to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-${{ env.AZURE_ENV_NAME }}
          package: ./dist
      
      - name: Verify B2C Configuration
        run: |
          echo "Verifying B2C configuration in Azure Web App..."
          az webapp config appsettings list --name app-${{ env.AZURE_ENV_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query "[?name.startsWith('VITE_B2C_')].{Name:name, Value:value}" --output table
      
      - name: Logout from Azure
        run: az logout
        if: always()
