name: Azure CI/CD for React App with Entra External ID

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_ENV_NAME: a-riff-in-react
  AZURE_LOCATION: westus
  SHARED_SQL_SERVER_NAME: sequitur-sql-server
  SHARED_SQL_SERVER_RG: db-rg

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build React app
        run: npm run build
        env: 
          # These placeholder values are needed for build but will be replaced by actual values in Azure
          VITE_ENTRA_CLIENT_ID: "placeholder-for-build"
          VITE_ENTRA_TENANT_ID: "placeholder-for-build"
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: Deploy Azure Infrastructure with Entra External ID Configuration
        id: deploy-bicep
        run: |
          az deployment group create \
            --resource-group riffinreact-rg \
            --template-file ./infra/main.bicep \
            --parameters \
              environmentName=${{ env.AZURE_ENV_NAME }} \
              location=${{ env.AZURE_LOCATION }} \
              externalTenantId=${{ secrets.ENTRA_TENANT_ID }} \
              externalClientId=${{ secrets.ENTRA_CLIENT_ID }} \
              sqlAdminPassword=${{ secrets.SQL_ADMIN_PASSWORD }} \
              sharedSqlServerName=${{ env.SHARED_SQL_SERVER_NAME }} \
              sharedSqlServerResourceGroupName=${{ env.SHARED_SQL_SERVER_RG }} \
            --name a-riff-in-react-${{ github.run_number }} \
            --verbose
      - name: Deploy React app to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_ENV_NAME }}
          package: ./dist
      
      - name: Verify Entra External ID Configuration
        run: |
          echo "Verifying Entra External ID configuration in Azure Web App..."
          az webapp config appsettings list --name app-${{ env.AZURE_ENV_NAME }} --resource-group riffinreact-rg --query "[?contains(name, 'VITE_ENTRA_')].{Name:name, Value:value}" --output table
      
      - name: Logout from Azure
        run: az logout
        if: always()
