name: Deploy Azure Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Bicep template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./infra/main.bicep
          parameters: >
            environmentName=${{ secrets.AZURE_ENV_NAME }}
            location=${{ secrets.AZURE_LOCATION }}
            b2cTenantName=${{ secrets.B2C_TENANT_NAME }}
            b2cClientId=${{ secrets.B2C_CLIENT_ID }}
            b2cSigninPolicy=${{ secrets.B2C_SIGNIN_POLICY }}
            sqlAdminPassword=${{ secrets.SQL_ADMIN_PASSWORD }}
      
      - name: Azure Logout
        run: az logout
        if: always()
