name: Deploy React App to Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'package.json'
      - 'vite.config.ts'
      - 'tsconfig.json'
      - '.github/workflows/deploy-app.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build React app
        run: npm run build
        env:
          VITE_B2C_CLIENT_ID: ${{ secrets.B2C_CLIENT_ID }}
          VITE_B2C_TENANT_NAME: ${{ secrets.B2C_TENANT_NAME }}
          VITE_B2C_SIGNIN_POLICY: ${{ secrets.B2C_SIGNIN_POLICY }}
          VITE_REDIRECT_URI: https://app-${{ secrets.AZURE_ENV_NAME }}.azurewebsites.net
          VITE_POST_LOGOUT_URI: https://app-${{ secrets.AZURE_ENV_NAME }}.azurewebsites.net
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-${{ secrets.AZURE_ENV_NAME }}
          package: ./dist
      
      - name: Azure Logout
        run: az logout
        if: always()
